use compre_melhor_db;
select * from partner;

INSERT INTO manufacturer(`name`, `date_created`, `last_updated`) values ('HELLMANS', '2016-07-08 09:40:26', '2016-07-08 09:40:26');
INSERT INTO partner(`name`, `date_created`, `last_updated`) values ('Supermercado da gente', '2016-07-08 09:40:26', '2016-07-08 09:40:26');
insert into category(`name`, `date_created`, `last_updated`) values ('Mercearia' ,now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Saúde e Beleza', Now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Limpeza', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Frios', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Congelados', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Higiene Pessoal', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Farmácia', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Farinha e Grãos', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Sobremesas', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Bomboniere', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Brinquedos', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Pet Shop', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Bebidas', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Bebidas Alcóolicas', now(), now());
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Pão de Mel PAN 100g com 8 Unidades', '', 'PCT', '1380556511236', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Sabão em Pó OMO Multiação Poder Acelerador 2kg', '', 'KG', '1380556511342', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Detergente para Máquina de Lavar Louça SUN 1kg ', '', 'KG', '1380556511199', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Queijo Cottage Light TAEQ 400g', '', 'UN', '1380556511182', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Peito de Pato sem Osso Congelado VILLA GERMÂNIA 480g', '', 'UN', '1380556511175', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Grão de Bico YOKI Pacote 500g', '', 'PCT', '1380556511168', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Refrigerante COCA COLA Zero Garrafa 1,5 Litros com 4 Unidades', '', 'PCT', '1380556511151', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Iogurte Grego Sabor Frutas Amarelas VIGOR 100g', '', 'UN', '1380556511144', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Creme Dental SENSODINE Repair & Protect 100g', '', 'UN', '1380556511137', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511236'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511342'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511199'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511182'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511175'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511168'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511151'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511144'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511137'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 5.69, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511236')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 12.8, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511342')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (50, 33.99, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511199')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 12.9, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511182')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 38.99, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511175')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 9.59, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511168')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 19, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511151')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 2, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511144')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 4.9, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511137')), now(), now(), 0);
use compre_melhor_db;
select * from partner;

INSERT INTO manufacturer(`name`, `date_created`, `last_updated`) values ('HELLMANS', '2016-07-08 09:40:26', '2016-07-08 09:40:26');
INSERT INTO partner(`name`, `date_created`, `last_updated`) values ('Supermercado da gente', '2016-07-08 09:40:26', '2016-07-08 09:40:26');
insert into category(`name`, `date_created`, `last_updated`) values ('Mercearia' ,now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Saúde e Beleza', Now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Limpeza', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Frios', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Congelados', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Higiene Pessoal', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Farmácia', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Farinha e Grãos', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Sobremesas', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Bomboniere', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Brinquedos', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Pet Shop', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Bebidas', now(), now());
insert into category(`name`, `date_created`, `last_updated`) values ('Bebidas Alcóolicas', now(), now());
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Pão de Mel PAN 100g com 8 Unidades', '', 'PCT', '1380556511236', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Sabão em Pó OMO Multiação Poder Acelerador 2kg', '', 'KG', '1380556511342', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Detergente para Máquina de Lavar Louça SUN 1kg ', '', 'KG', '1380556511199', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Queijo Cottage Light TAEQ 400g', '', 'UN', '1380556511182', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Peito de Pato sem Osso Congelado VILLA GERMÂNIA 480g', '', 'UN', '1380556511175', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Grão de Bico YOKI Pacote 500g', '', 'PCT', '1380556511168', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Refrigerante COCA COLA Zero Garrafa 1,5 Litros com 4 Unidades', '', 'PCT', '1380556511151', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Iogurte Grego Sabor Frutas Amarelas VIGOR 100g', '', 'UN', '1380556511144', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
INSERT INTO sku (`name`,`description`,`unit`,`code`, `status`,`date_created`,`last_updated`, `category_id`,`manufacturer_id`)VALUES ('Creme Dental SENSODINE Repair & Protect 100g', '', 'UN', '1380556511137', 'PUBLICADO' ,now(), now(), (select id from category where name = 'Mercearia'),(select id from manufacturer where name = 'HELLMANS'));
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511236'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511342'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511199'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511182'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511175'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511168'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511151'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511144'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
insert into sku_partner(`sku_id`, `partner_id`, `date_created`, `last_updated`) values ((select id from sku where code = '1380556511137'), (select id from partner where name like '%da gente%'), '2016-07-08 09:40:26', '2016-07-08 09:40:26' );
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 5.69, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511236')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 12.8, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511342')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (50, 33.99, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511199')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 12.9, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511182')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 38.99, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511175')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 9.59, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511168')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 19, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511151')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 2, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511144')), now(), now(), 0);
INSERT INTO `stock` ( `quantity`,`unit_price`,`sku_partner_id`,`date_created`,`last_updated`,`version`) VALUES (100, 4.9, (select id from sku_partner where sku_id = (select id from sku where code = '1380556511137')), now(), now(), 0);
